# Generated by Django 5.0.1 on 2024-02-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CovidData",
            fields=[
                ("Country", models.CharField(max_length=255)),
                ("SNo", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("ObservationDate", models.DateField()),
                (
                    "Province_State",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("LastUpdate", models.DateTimeField()),
                ("Confirmed", models.FloatField()),
                ("Deaths", models.FloatField()),
                ("Recovered", models.FloatField()),
                (
                    "ISO3166_CountryCode",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                ("Latitude", models.FloatField(blank=True, null=True)),
                ("Longitude", models.FloatField(blank=True, null=True)),
                (
                    "coordinates",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mercator_x", models.FloatField(blank=True, null=True)),
                ("mercator_y", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
