# Generated by Django 4.2.10 on 2024-02-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PubMedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("abstract", models.TextField()),
                ("author", models.CharField(max_length=255)),
                ("date_of_publication", models.DateField()),
                ("pubmed_link", models.URLField()),
            ],
        ),
    ]
