# Generated by Django 4.2.10 on 2024-02-19 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_pubmedrecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PubMedRecord",
        ),
    ]
